//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statybviete
    {
        public Statybviete()
        {
            this.Darbuotojas = new HashSet<Darbuotojas>();
        }
    
        public int Id { get; set; }
        public string Tipas { get; set; }
        public int Plotas { get; set; }
        public string Adresas { get; set; }
        public Nullable<System.DateTime> Pradzia { get; set; }
        public Nullable<System.DateTime> Pabaiga { get; set; }
    
        public virtual ICollection<Darbuotojas> Darbuotojas { get; set; }
    }
}
