//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statybininkas
    {
        public long AK { get; set; }
        public string Kvalifikacija { get; set; }
    
        public virtual Darbuotojas DarbuotojoAK { get; set; }
    }
}
